# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: hydrology

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("httr2")'
        
    # Run R script
    - name: Scrape
      run: Rscript get_data.R
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name Otoliths
        git config --local user.email "ly_ding@126.com"
        git add water/*
        git add rain/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.TOKEN}}
        username: github-actions
